<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="SATISH-PC" name="Verify addition and Subtraction of two numbers" tests="2" failures="1" timestamp="7 Feb 2018 15:23:19 GMT" time="0.115" errors="0">
  <testcase name="add" time="0.021" classname="org.ej.learning.Maths">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [222] but found [220]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	expected [222] but found [220]
	at org.ej.learning.Maths.add(Maths.java:96)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- add -->
  <testcase name="subtract" time="0.003" classname="org.ej.learning.Maths"/>
</testsuite> <!-- Verify addition and Subtraction of two numbers -->
